name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build web app
        run: npm run build
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init semdex mu.semdex.app --web-dir=dist
          npx cap add android
          npx cap sync
      
      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon
      
      - name: Sign APK (optional)
        run: echo "APK built successfully"
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: semdex-apk
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30
